#pragma once
#include <Windows.h>
#include <dwmapi.h>
#include <d3d11.h>
#include <cstdio> 
#include <cstring> 
#include <fstream> 
#include <cstdlib> 
#include <iostream>
#include <vector>
#include <thread>
#include "external/imgui/imgui.h"
#include "external/imgui/imgui_impl_dx11.h"
#include "external/imgui/imgui_impl_win32.h"
#include "CsItems/globals.h"
#include "helpers/helpers.h"
#include "CsItems/Entity.h"
#include "CsItems/hacks.h"
#include "fonts/Fonts.h"
#include "external/imgui/imgui.h"
#include "external/imgui/imgui_impl_dx11.h"
#include "external/imgui/imgui_impl_win32.h"
#include "helpers/menu.h"